module.exports = {
  apps: [
    {
      name: 'commerce-api',
      cwd: '/home/hqdu/quangdu/webbanhang/apps/api',
      script: 'dist/main.js',
      interpreter: 'node',
      env_file: '/home/hqdu/quangdu/webbanhang/.env',
      env: {
        APP_PORT: 3002,
        NODE_ENV: 'development',
        POSTGRES_HOST: 'localhost',
        POSTGRES_PORT: 54362,
        POSTGRES_USER: 'commerce_user',
        POSTGRES_DB: 'ai_commerce',
        REDIS_HOST: 'localhost',
        REDIS_PORT: 63789,
      },
      instances: 1,
      autorestart: true,
      watch: false,
      max_memory_restart: '512M',
      error_file: '/home/hqdu/quangdu/webbanhang/logs/api-error.log',
      out_file: '/home/hqdu/quangdu/webbanhang/logs/api-out.log',
      log_date_format: 'YYYY-MM-DD HH:mm:ss',
    },
    {
      name: 'commerce-web',
      cwd: '/home/hqdu/quangdu/webbanhang/apps/web',
      script: 'node_modules/.bin/next',
      args: 'start -p 3003',
      env: {
        NODE_ENV: 'production',
        PORT: 3003,
      },
      instances: 1,
      autorestart: true,
      watch: false,
      max_memory_restart: '512M',
      error_file: '/home/hqdu/quangdu/webbanhang/logs/web-error.log',
      out_file: '/home/hqdu/quangdu/webbanhang/logs/web-out.log',
      log_date_format: 'YYYY-MM-DD HH:mm:ss',
    },
  ],
};
